# Generated by Django 6.0.4 on 2026-04-19 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('normal_phone', 'Normal - Single Face w/ Phone'), ('normal_no_phone', 'Normal - Single Face'), ('no_face_phone', 'No Face - Phone Detected'), ('no_face_no_phone', 'No Face Detected'), ('multiple_faces_phone', 'Multiple Faces w/ Phone'), ('multiple_faces_no_phone', 'Multiple Faces')], max_length=25)),
                ('face_count', models.IntegerField(default=0)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('phone_detected', models.BooleanField(default=False)),
                ('phone_confidence', models.FloatField(default=0.0)),
                ('risk_score', models.CharField(default='low', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
