# Generated by Django 6.0.4 on 2026-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlog',
            name='status',
            field=models.CharField(choices=[('normal_phone', 'Normal - Single Face w/ Phone'), ('normal_no_phone', 'Normal - Single Face'), ('no_face_phone', 'No Face - Phone Detected'), ('no_face_no_phone', 'No Face Detected'), ('multiple_faces_phone', 'Multiple Faces w/ Phone'), ('multiple_faces_no_phone', 'Multiple Faces')], max_length=50),
        ),
    ]
